%FULLFACTORIAL [size + complexity]
function [ExperimentData,LagVector,Delta]=ffAnalysisINIT

autoRegressionCoefficients=[0.9,0.9,0.1];
% dLower=[30,25,20,15,10,5,0,-5,-10];
% dUpper=[60,55,50,45,40,35,30,25,20];
dLower=[0,0,0,0,0,0,0,0,0];
dUpper=[30,30,30,30,30,30,30,30,30];
settingOutliers=true;
settingStartSet=autoRegressionCoefficients;
settingYNoise=0.05;
settingLagNumber=3;
settingXNoise=[0.01,0.01,0.01];
rng(1,'twister')
[xSize1Calib,~,ttXSize1Calib,ttYSize1Calib,LagVector,~,~,Delta]=SynthDataGeneration(100,1,...
    'Outliers',settingOutliers,...
    'startSet',settingStartSet,...
    'YNoise',settingYNoise,...
    'lagNum',settingLagNumber,...
    'XNoise',settingXNoise,...
    'deltaUpper',dUpper,...
    'deltaLower',dLower...
    );
[xSize2Calib,~,ttXSize2Calib,ttYSize2Calib]=SynthDataGeneration(1000,1,...
    'Outliers',settingOutliers,...
    'startSet',settingStartSet,...
    'YNoise',settingYNoise,...
    'lagNum',settingLagNumber,...
    'XNoise',settingXNoise,...
    'deltaUpper',dUpper,...
    'deltaLower',dLower...
    );
[xSize3Calib,~,ttXSize3Calib,ttYSize3Calib]=SynthDataGeneration(10000,1,...
    'Outliers',settingOutliers,...
    'startSet',settingStartSet,...
    'YNoise',settingYNoise,...
    'lagNum',settingLagNumber,...
    'XNoise',settingXNoise,...
    'deltaUpper',dUpper,...
    'deltaLower',dLower...
    );
rng(now,'twister')
[xSize1Test,~,ttXSize1Test,ttYSize1Test]=SynthDataGeneration(100,1,...
    'Outliers',settingOutliers,...
    'startSet',settingStartSet,...
    'YNoise',settingYNoise,...
    'lagNum',settingLagNumber,...
    'XNoise',settingXNoise,...
    'deltaUpper',dUpper,...
    'deltaLower',dLower...
    );
[xSize2Test,~,ttXSize2Test,ttYSize2Test]=SynthDataGeneration(1000,1,...
    'Outliers',settingOutliers,...
    'startSet',settingStartSet,...
    'YNoise',settingYNoise,...
    'lagNum',settingLagNumber,...
    'XNoise',settingXNoise,...
    'deltaUpper',dUpper,...
    'deltaLower',dLower...
    );
[xSize3Test,~,ttXSize3Test,ttYSize3Test]=SynthDataGeneration(10000,1,...
    'Outliers',settingOutliers,...
    'startSet',settingStartSet,...
    'YNoise',settingYNoise,...
    'lagNum',settingLagNumber,...
    'XNoise',settingXNoise,...
    'deltaUpper',dUpper,...
    'deltaLower',dLower...
    );

%%%
%calib
ExperimentData.hundred.calib.X=xSize1Calib;
ExperimentData.hundred.calib.TT=ttXSize1Calib;
ExperimentData.hundred.calib.C1=ttYSize1Calib.y_lin;
ExperimentData.hundred.calib.C2=ttYSize1Calib.y_interactions;
ExperimentData.hundred.calib.C3=ttYSize1Calib.y_enzyme;
%test
ExperimentData.hundred.test.X=xSize1Test;
ExperimentData.hundred.test.TT=ttXSize1Test;
ExperimentData.hundred.test.C1=ttYSize1Test.y_lin;
ExperimentData.hundred.test.C2=ttYSize1Test.y_interactions;
ExperimentData.hundred.test.C3=ttYSize1Test.y_enzyme;
%%%
%calib
ExperimentData.thousand.calib.X=xSize2Calib;
ExperimentData.thousand.calib.TT=ttXSize2Calib;
ExperimentData.thousand.calib.C1=ttYSize2Calib.y_lin;
ExperimentData.thousand.calib.C2=ttYSize2Calib.y_interactions;
ExperimentData.thousand.calib.C3=ttYSize2Calib.y_enzyme;
%test
ExperimentData.thousand.test.X=xSize2Test;
ExperimentData.thousand.test.TT=ttXSize2Test;
ExperimentData.thousand.test.C1=ttYSize2Test.y_lin;
ExperimentData.thousand.test.C2=ttYSize2Test.y_interactions;
ExperimentData.thousand.test.C3=ttYSize2Test.y_enzyme;
%%%
%calib
ExperimentData.tenThousand.calib.X=xSize3Calib;
ExperimentData.tenThousand.calib.TT=ttXSize3Calib;
ExperimentData.tenThousand.calib.C1=ttYSize3Calib.y_lin;
ExperimentData.tenThousand.calib.C2=ttYSize3Calib.y_interactions;
ExperimentData.tenThousand.calib.C3=ttYSize3Calib.y_enzyme;
%test
ExperimentData.tenThousand.test.X=xSize3Test;
ExperimentData.tenThousand.test.TT=ttXSize3Test;
ExperimentData.tenThousand.test.C1=ttYSize3Test.y_lin;
ExperimentData.tenThousand.test.C2=ttYSize3Test.y_interactions;
ExperimentData.tenThousand.test.C3=ttYSize3Test.y_enzyme;
%%%







