% function [ResultsTruthfulness,ResultsR2]=ffAnalysisCORE()
[ExperimentData,LagVect,Delta]=ffAnalysisINIT;
rng(1,'twister')
% LagVect=[45,40,35,30,25,20,15,10,5];
ffFactors=fullfact([3,3]);
sizeFactors=cellstr(["100___","1000__","10000_"])';
complexityFactors=cellstr(["linear","interactions","power_ratio"])';
rowNames=strcat(sizeFactors(ffFactors(:,1)),complexityFactors(ffFactors(:,2)));
generalOptimOptions=struct(...
    'IDE',struct(...
    'nPop',300,...
    'maxGeneration',30,...
    'maxIter',30,...
    'CR',0.1,...
    'F',0.5...
    ),...
    'GA',struct(...
    'nPop',300,...
    'maxGeneration',30,...
    'CR',0.1,...
    'MR',0.1,...
    'Elitism',0.1...
    )...
    );

methods=cellstr([...
    "P_Correlation",...
    "S_Correlation",...
    "K_Correlation",...
    "MIC",...
    "N-norm",...
    "Procrustes",...
    "MI-Sousa",...
    "MI-Index",...
    "PLS-SR",...
    "PLS-REG",...
    "DistanceCorrelation",...
    "VTR-LS",...
    "VTR-COSE",...
    "GA-ITSS",...
    "RandomForest"]);
ResultsR2=table('Size',[9,15],'VariableTypes',repmat("doublenan",[1,15]),'VariableNames',methods,'RowNames',rowNames);
ResultsTruthfulness=table('Size',[9,15],'VariableTypes',repmat("doublenan",[1,15]),'VariableNames',methods,'RowNames',rowNames);
sizeField=cellstr(["hundred","thousand","tenThousand"]);
complexityField=cellstr(["C1","C2","C3"]);
tic
vtdePc=zeros(9,9);
vtdeSc=zeros(9,9);
vtdeKc=zeros(9,9);
vtdeMic=zeros(9,9);
vtdeMgx=zeros(9,9);
vtdeProcrustes=zeros(9,9);
vtdeMiSousa=zeros(9,9);
vtdeMiIndex=zeros(9,9);
vtdeDCorrelation=zeros(9,9);
vtdePLSSR=zeros(9,9);
vtdePLSREG=zeros(9,9);
vtdeVTRLS=zeros(9,9);
vtdeVTRGMM=zeros(9,9);
vtdeRandomForest=zeros(9,9);
for experiment=1:9
    xCalib=     ExperimentData.(sizeField{ffFactors(experiment,1)}).calib.X;
    ttXCalib=   ExperimentData.(sizeField{ffFactors(experiment,1)}).calib.TT;
    yCalib=     ExperimentData.(sizeField{ffFactors(experiment,1)}).calib...
        .(complexityField{ffFactors(experiment,2)});
    xTest=      ExperimentData.(sizeField{ffFactors(experiment,1)}).test.X;
    ttXTest=    ExperimentData.(sizeField{ffFactors(experiment,1)}).test.TT;
    yTest=      ExperimentData.(sizeField{ffFactors(experiment,1)}).test...
        .(complexityField{ffFactors(experiment,2)});
    ttXCalib=ttXCalib(:,(std(ttXCalib{:,:},1))>0);
    ttXTest=ttXTest(:,(std(ttXTest{:,:},1))>0);
    [vtdePc(experiment,:),distancePC]=ffAnalysisCC(ttXCalib,yCalib,Delta,...
        "CCType","Pearson");
    ResultsTruthfulness{experiment,"P_Correlation"}=distancePC;
    [vtdeSc(experiment,:),distanceSC]=ffAnalysisCC(ttXCalib,yCalib,Delta,...
        "CCType","Spearman");
    ResultsTruthfulness{experiment,"S_Correlation"}=distanceSC;
    [vtdeKc(experiment,:),distanceKC]=ffAnalysisCC(ttXCalib,yCalib,Delta,...
        "CCType","Kendall");
    ResultsTruthfulness{experiment,"K_Correlation"}=distanceKC;
    [vtdeMic(experiment,:),distanceMIC]=ffAnalysisMIC(ttXCalib,yCalib,Delta);
    ResultsTruthfulness{experiment,"MIC"}=distanceMIC;
    [vtdeMgx(experiment,:),distanceMGX]=ffAnalysisMGX(xCalib,yCalib,Delta);
    ResultsTruthfulness{experiment,"N-norm"}=distanceMGX;
    [vtdeProcrustes(experiment,:),distancePRO]=ffAnalysisPROCRUSTES(ttXCalib,yCalib,Delta);
    ResultsTruthfulness{experiment,"Procrustes"}=distancePRO;
    [vtdeMiIndex(experiment,:),distanceMIIDX]=ffAnalysisMIINDEX(ttXCalib,yCalib,Delta);
    ResultsTruthfulness{experiment,"MI-Index"}=distanceMIIDX;
    [vtdeMiSousa(experiment,:),distanceMISOUSA]=ffAnalysisMISOUSA(ttXCalib,yCalib,Delta);
    ResultsTruthfulness{experiment,"MI-Sousa"}=distanceMISOUSA;
    [vtdeDCorrelation(experiment,:),distanceDCORR]=ffAnalysisDISTANCE(ttXCalib,yCalib,Delta);
    ResultsTruthfulness{experiment,"DistanceCorrelation"}=distanceDCORR;
    [vtdePLSSR(experiment,:),distancePLSSR]=ffAnalysisPLS(ttXCalib,yCalib,Delta,...
        "PLSType","SR");
    ResultsTruthfulness{experiment,"PLS-SR"}=distancePLSSR;
    [vtdePLSREG(experiment,:),distancePLSREG]=ffAnalysisPLS(ttXCalib,yCalib,Delta,...
        "PLSType","REG");
    ResultsTruthfulness{experiment,"PLS-REG"}=distancePLSREG;
    [vtdeVTRLS(experiment,:),distanceVTRLS]=ffAnalysisVTR(xCalib,yCalib,Delta,...
        "VTRType","LS");
    ResultsTruthfulness{experiment,"VTR-LS"}=distanceVTRLS;
    [vtdeVTRGMM(experiment,:),distanceVTRGMM]=ffAnalysisVTR(xCalib,yCalib,Delta,...
        "VTRType","GMM");
    ResultsTruthfulness{experiment,"VTR-GMM"}=distanceVTRGMM;
    [vtdeRandomForest(experiment,:),distanceRF]=ffAnalysisRF(ttXCalib,yCalib,Delta);
    ResultsTruthfulness{experiment,"RandomForest"}=distanceRF;
    
    
    
end
toc